application: tensile-topic
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: .*
  script: app.app
  secure: always

libraries:
- name: ssl
  version: latest

skip_files:
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?\..*$
- ^env$
- ^\.git$
- ^\.ropeproject$
